//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARP_Spoofer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARP_Spoofer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] PacketDotNet {
            get {
                object obj = ResourceManager.GetObject("PacketDotNet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;/home/cmorgan/hdd/packetnet_git/PacketDotNet/bin/Release/PacketDotNet&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:PacketDotNet.ApplicationPacket&quot;&gt;
        ///            &lt;summary&gt;
        ///            Represents an application layer packet as described at http://en.wikipedia.org/wiki/Application_Layer
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:PacketDotNet.ApplicationPacket.#ctor&quot;&gt;
        ///            &lt;summary&gt;
        ///            ApplicationPacket [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PacketDotNet1 {
            get {
                return ResourceManager.GetString("PacketDotNet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] PcapDotNet_Base {
            get {
                object obj = ResourceManager.GetObject("PcapDotNet_Base", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;PcapDotNet.Base&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:PcapDotNet.Base.TypeExtensions&quot;&gt;
        ///            &lt;summary&gt;
        ///            Extension methods for Type.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:PcapDotNet.Base.TypeExtensions.GetEnumValues``1(System.Type)&quot;&gt;
        ///            &lt;summary&gt;
        ///            Returns all the possible values for the given enum type.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PcapDotNet_Base1 {
            get {
                return ResourceManager.GetString("PcapDotNet_Base1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] PcapDotNet_Core {
            get {
                object obj = ResourceManager.GetObject("PcapDotNet_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] PcapDotNet_Core_Extensions {
            get {
                object obj = ResourceManager.GetObject("PcapDotNet_Core_Extensions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;PcapDotNet.Core.Extensions&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:PcapDotNet.Core.Extensions.PacketCommunicatorExtensions&quot;&gt;
        ///            &lt;summary&gt;
        ///            Different extension methods for PacketCommunicator class.
        ///            &lt;seealso cref=&quot;T:PcapDotNet.Core.PacketCommunicator&quot;/&gt;
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:PcapDotNet.Core.Extensions.PacketCommunicatorExtensions.ReceivePackets(Pc [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PcapDotNet_Core_Extensions1 {
            get {
                return ResourceManager.GetString("PcapDotNet_Core_Extensions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &quot;PcapDotNet.Core&quot;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;P:PcapDotNet.Core.SamplingMethodOneEveryCount.Value&quot;&gt;
        ///            &lt;summary&gt;
        ///Indicates the number of packets (minus 1) that must be discarded before one packet got accepted. 
        ///In other words, if &apos;value = 10&apos;, the first packet is returned to the caller, while the following 9 are discarded.
        ///&lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:PcapDotNet.Core.SamplingMethodOneEvery [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PcapDotNet_Core1 {
            get {
                return ResourceManager.GetString("PcapDotNet_Core1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] PcapDotNet_Packets {
            get {
                object obj = ResourceManager.GetObject("PcapDotNet_Packets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;PcapDotNet.Packets&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:PcapDotNet.Packets.Transport.TransportDatagram&quot;&gt;
        ///            &lt;summary&gt;
        ///            Contains the common part of UDP and TCP.
        ///            
        ///            &lt;para&gt;
        ///            Format:
        ///            &lt;pre&gt;
        ///            +-----+-------------+----------+-----+-----+-----+-----+-----+-----+------------------+
        ///            | Bit | 0-4         | 4-9      | 10  | 11  | 12  | 13   [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PcapDotNet_Packets1 {
            get {
                return ResourceManager.GetString("PcapDotNet_Packets1", resourceCulture);
            }
        }
    }
}
